# Laboratorium 4 — NumPy zaawansowane
**Autor:** Jacek Nocoń

In [27]:
import numpy as np

Ćwiczenie 1: Broadcasting — zastosowania biznesowe (20min)

In [28]:
# Ceny 4 produktów w 3 sklepach
ceny = np.array([[29.99, 31.99, 28.99], # Produkt A
[49.99, 52.99, 47.99], # Produkt B
[14.99, 15.99, 13.99], # Produkt C
[99.99, 104.99, 94.99]]) # Produkt D
sklepy = ['Centrum', 'Galeria', 'Online']
produkty = ['A', 'B', 'C', 'D']
print(f"Kształt macierzy: {ceny.shape}") # (4, 3)

Kształt macierzy: (4, 3)


In [29]:
# Zadanie 1a: Inflacja 5% (Broadcasting: macierz * skalar)
ceny_inflacja = ceny * 1.05
print("1a. Wszystkie ceny po inflacji 5%:")
print(np.round(ceny_inflacja, 2))

1a. Wszystkie ceny po inflacji 5%:
[[ 31.49  33.59  30.44]
 [ 52.49  55.64  50.39]
 [ 15.74  16.79  14.69]
 [104.99 110.24  99.74]]


In [30]:
# Zadanie 1b: Stwórz array z cenami po rabacie. Każdy sklep daje inny rabat: Centrum 10%, Galeria 5%, Online 15%.
rabaty = np.array([0.10, 0.05, 0.15])
ceny_po_rabacie = ceny * (1 - rabaty)
print("\nZadanie 1b - Wynik (ceny po rabacie):")
print(np.round(ceny_po_rabacie, 2))



Zadanie 1b - Wynik (ceny po rabacie):
[[26.99 30.39 24.64]
 [44.99 50.34 40.79]
 [13.49 15.19 11.89]
 [89.99 99.74 80.74]]


In [31]:
# Zadanie 1c: Oblicz koszt zakupu każdego produktu. Każdy produkt ma inną marżę: A=30%, B=40%, C=25%, D=50%
marza = np.array([[0.30], [0.40], [0.25], [0.50]])
koszt_zakupu = ceny / (1 + marza)
print("\nZadanie 1c - Wynik (koszt zakupu):")
print(np.round(koszt_zakupu, 2))




Zadanie 1c - Wynik (koszt zakupu):
[[23.07 24.61 22.3 ]
 [35.71 37.85 34.28]
 [11.99 12.79 11.19]
 [66.66 69.99 63.33]]


In [32]:
# Zadanie 1d: Wyświetl najtańszy sklep dla każdego produktu.
najtanszy_idx = np.argmin(ceny, axis=1)
print("\nZadanie 1d - Najtańszy sklep dla każdego produktu:")
for i, idx in enumerate(najtanszy_idx):
    print(f" - Produkt {produkty[i]}: {sklepy[idx]}")


Zadanie 1d - Najtańszy sklep dla każdego produktu:
 - Produkt A: Online
 - Produkt B: Online
 - Produkt C: Online
 - Produkt D: Online


Ćwiczenie 2: Reshape i łączenie danych (20 min)

In [33]:
# Zadanie 2a — Reshape
# Dane miesięczne z jednego roku (flat)
dane_flat = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
# Przekształć na kwartały (4 kwartały × 3 miesiące)
kwartaly = dane_flat.reshape(4, 3)
print(f"Kwartały:\n{kwartaly}")
print(f"Suma per kwartał: {kwartaly.sum(axis=1)}")
print(f"Najlepszy kwartał: Q{kwartaly.sum(axis=1).argmax() + 1}")

Kwartały:
[[120 135  98]
 [142 167 189]
 [201 178 156]
 [143 198 221]]
Suma per kwartał: [353 498 535 562]
Najlepszy kwartał: Q4


In [34]:
# Zadanie 2b — Stacking
# Dane z 3 oddziałów (osobne tablice)
warszawa = np.array([150, 160, 170, 180])
krakow = np.array([120, 130, 140, 150])
wroclaw = np.array([90, 100, 110, 120])
# Połącz w macierz (3 oddziały × 4 kwartały)
wszystkie = np.vstack([warszawa, krakow, wroclaw])
print(f"Wszystkie:\n{wszystkie}")
print(f"Suma per oddział: {wszystkie.sum(axis=1)}")
print(f"Suma per kwartał: {wszystkie.sum(axis=0)}")

Wszystkie:
[[150 160 170 180]
 [120 130 140 150]
 [ 90 100 110 120]]
Suma per oddział: [660 540 420]
Suma per kwartał: [360 390 420 450]


In [35]:
# Zadanie 2c: Sprzedaż 6 produktów x 2 miesiące
sprzedaz_flat = np.array([100, 200, 150, 300, 250, 180, 120, 220, 170, 310, 260, 190])
sprzedaz_2d = sprzedaz_flat.reshape(6, 2)
srednia_produkt = sprzedaz_2d.mean(axis=1)
print(f"2c. Średnia sprzedaż per produkt: {srednia_produkt}")

2c. Średnia sprzedaż per produkt: [150. 225. 215. 170. 240. 225.]


In [36]:
# Zadanie 2d: Flatten i concatenate
wektor = kwartaly.flatten()
wektor_13 = np.concatenate([wektor, np.array([235])])
print(f"2d. Długość tablicy po dodaniu 13. miesiąca: {len(wektor_13)}")

2d. Długość tablicy po dodaniu 13. miesiąca: 13


Ćwiczenie 3: Analiza danych finansowych (30 min)

In [37]:
np.random.seed(2026)
# 8 pracowników, dane roczne
pracownicy = ['Anna', 'Jan', 'Ewa', 'Marek', 'Kasia', 'Piotr', 'Zofia', 'Tomek']
pensje = np.array([5500, 7200, 4800, 9100, 6300, 4200, 8500, 5800])
staz = np.array([3, 8, 2, 15, 5, 1, 12, 4])
oceny = np.array([4.2, 3.8, 4.5, 4.0, 4.7, 3.5, 4.3, 3.9])
# Sprzedaż miesięczna 4 produktów przez 6 miesięcy
produkty_nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Akcesorium']
sprzedaz = np.random.randint(20, 200, size=(4, 6))
ceny_produktow = np.array([3500, 1800, 2500, 150])

In [38]:
# 3a. Statystyki
iqr = np.percentile(pensje, 75) - np.percentile(pensje, 25)
print(f"3a. Średnia: {pensje.mean()}, Mediana: {np.median(pensje)}, IQR: {iqr}")

3a. Średnia: 6425.0, Mediana: 6050.0, IQR: 2200.0


In [39]:
# 3b. System premii 
premie = np.where(oceny >= 4.5, 2000, np.where(oceny >= 4.0, 1000, 0))
nowe_wynagrodzenie = pensje + premie
print(f"3b. Najwyższa premia: {pracownicy[premie.argmax()]} ({premie.max()} zł)")


3b. Najwyższa premia: Ewa (2000 zł)


In [40]:
# 3c. Ranking
kolejnosc = np.argsort(pensje)[::-1]
print("\n3c. Ranking pracowników wg pensji:")
for i, idx in enumerate(kolejnosc, 1):
    print(f" {i}. {pracownicy[idx]} | {pensje[idx]} zł | staż: {staz[idx]} lat")



3c. Ranking pracowników wg pensji:
 1. Marek | 9100 zł | staż: 15 lat
 2. Zofia | 8500 zł | staż: 12 lat
 3. Jan | 7200 zł | staż: 8 lat
 4. Kasia | 6300 zł | staż: 5 lat
 5. Tomek | 5800 zł | staż: 4 lat
 6. Anna | 5500 zł | staż: 3 lat
 7. Ewa | 4800 zł | staż: 2 lat
 8. Piotr | 4200 zł | staż: 1 lat


In [41]:
# 3d. Korelacja
r_staz_pensja = np.corrcoef(staz, pensje)[0, 1]
print(f"\n3d. Korelacja staż vs pensja: {r_staz_pensja:.2f}")



3d. Korelacja staż vs pensja: 0.99


In [42]:
# 3e. Analiza sprzedaży
sprzedaz = np.random.randint(20, 200, size=(4, 6))
ceny_produktow = np.array([3500, 1800, 2500, 150])
przychod = sprzedaz * ceny_produktow.reshape(4, 1)
najlepszy_prod_idx = przychod.sum(axis=1).argmax()
print(f"3e. Najlepszy produkt: {['Laptop', 'Tablet', 'Smartfon', 'Akcesorium'][najlepszy_prod_idx]}")


3e. Najlepszy produkt: Laptop


Ćwiczenie 4: Generowanie danych (15 min)

In [43]:
wiek = np.clip(np.random.normal(35, 10, 100).astype(int), 18, None)
wydatki = np.clip(np.random.normal(500, 200, 100), 0, None)
wizyty = np.random.poisson(5, 100)


In [44]:
print("1. Statystyki opisowe:")
print(f"Wiek - średnia: {wiek.mean():.1f}, mediana: {np.median(wiek):.1f}, std: {wiek.std():.1f}, min: {wiek.min()}, max: {wiek.max()}")
print(f"Wydatki - średnia: {wydatki.mean():.1f}, mediana: {np.median(wydatki):.1f}, std: {wydatki.std():.1f}, min: {wydatki.min():.1f}, max: {wydatki.max():.1f}")
print(f"Wizyty - średnia: {wizyty.mean():.1f}, mediana: {np.median(wizyty):.1f}, std: {wizyty.std():.1f}, min: {wizyty.min()}, max: {wizyty.max()}")


1. Statystyki opisowe:
Wiek - średnia: 35.3, mediana: 36.0, std: 9.2, min: 18, max: 62
Wydatki - średnia: 506.1, mediana: 483.8, std: 206.4, min: 0.0, max: 982.3
Wizyty - średnia: 5.3, mediana: 5.0, std: 2.1, min: 1, max: 11


In [45]:
r_wiek_wydatki = np.corrcoef(wiek, wydatki)[0, 1]
print(f"\n2. Korelacja wiek vs wydatki: {r_wiek_wydatki:.2f}")


2. Korelacja wiek vs wydatki: 0.12


In [46]:
r_wizyty_wydatki = np.corrcoef(wizyty, wydatki)[0, 1]
print(f"3. Korelacja wizyty vs wydatki: {r_wizyty_wydatki:.2f}")


3. Korelacja wizyty vs wydatki: 0.09


In [47]:
sr = wydatki.mean()
sd = wydatki.std()
segment = np.where(wydatki > sr + sd, 'WYSOKI', 
          np.where(wydatki < sr - sd, 'NISKI', 'SREDNI'))


In [48]:
segmenty_unikalne, licznik = np.unique(segment, return_counts=True)
print("\n5. Liczba klientów w poszczególnych segmentach:")
for s, l in zip(segmenty_unikalne, licznik):
    print(f" - {s}: {l}")


5. Liczba klientów w poszczególnych segmentach:
 - NISKI: 15
 - SREDNI: 70
 - WYSOKI: 15
