# Laboratorium 3 — NumPy
**Autor:** Jacek

In [12]:
import numpy as np

In [13]:
# 1. Z listy
oceny = np.array([4.0, 3.5, 5.0, 4.5, 3.0, 4.0, 5.0])
print(f"Oceny: {oceny}")
print(f"Typ: {oceny.dtype}")

Oceny: [4.  3.5 5.  4.5 3.  4.  5. ]
Typ: float64


In [14]:
# 2. Zera — 10 elementów
zera = np.zeros(10)
print(f"Zera: {zera}")

Zera: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [15]:
# 3. Jedynki — macierz 3×5
jedynki = np.ones((3, 5))
print(f"Jedynki:\n{jedynki}")

Jedynki:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
# 4. Sekwencja od 0 do 100, co 10
dziesiatki = np.arange(0, 101, 10)
print(f"Dziesiątki: {dziesiatki}")

Dziesiątki: [  0  10  20  30  40  50  60  70  80  90 100]


In [17]:
# 5. 7 równomiernych punktów od 0 do 1
ulamki = np.linspace(0, 1, 7)
print(f"Ulamki: {ulamki}")

Ulamki: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [18]:
# 6. 20 losowych ocen od 2 do 5
np.random.seed(42)
losowe_oceny = np.random.randint(2, 6, size=20)
print(f"Losowe oceny: {losowe_oceny}")

Losowe oceny: [4 5 2 4 4 5 2 2 4 3 4 4 4 4 5 2 5 5 5 4]


In [19]:
# Zbadaj tablicę losowych ocen
print(f"shape: {losowe_oceny.shape}")
print(f"ndim: {losowe_oceny.ndim}")
print(f"size: {losowe_oceny.size}")
print(f"dtype: {losowe_oceny.dtype}")

shape: (20,)
ndim: 1
size: 20
dtype: int64


In [20]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
# Indeksy: 0 1 2 3 4 5 6 7 8 9 10 11
# Miesiące: Sty Lut Mar Kwi Maj Cze Lip Sie Wrz Paź Lis Gru

In [25]:
print(f"Styczeń: {miesiace_sprzedaz[0]}")

Styczeń: 120


In [26]:
print(f"Grudzień: {miesiace_sprzedaz[-1]}")

Grudzień: 221


In [27]:
print(f"Q1 (Sty-Mar): {miesiace_sprzedaz[0:3]}")

Q1 (Sty-Mar): [120 135  98]


In [28]:
print(f"Q4 (Ostatnie 3): {miesiace_sprzedaz[-3:]}")

Q4 (Ostatnie 3): [143 198 221]


In [29]:
print(f"Co drugi miesiąc: {miesiace_sprzedaz[::2]}")

Co drugi miesiąc: [120  98 167 201 156 198]


In [30]:
print(f"Od tyłu: {miesiace_sprzedaz[::-1]}")

Od tyłu: [221 198 143 156 178 201 189 167 142  98 135 120]


In [31]:
# Sprzedaż 4 produktów w 3 kwartałach
dane = np.array([
[120, 145, 167], # Produkt A
[89, 102, 95], # Produkt B
[234, 267, 289], # Produkt C
[56, 78, 91], # Produkt D
])
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']

In [32]:
print(f"Produkt A w Q2: {dane[0, 1]}")

Produkt A w Q2: 145


In [33]:
print(f"Cała sprzedaż Produktu C: {dane[2, :]}")

Cała sprzedaż Produktu C: [234 267 289]


In [34]:
print(f"Wszystkie produkty w Q1: {dane[:, 0]}")

Wszystkie produkty w Q1: [120  89 234  56]


In [35]:
print(f"Produkty B i C w Q2 i Q3:\n{dane[1:3, 1:3]}")

Produkty B i C w Q2 i Q3:
[[102  95]
 [267 289]]


In [36]:
nazwy = np.array(['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka','Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka'])
ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])

In [43]:
print(f"Średnia cena: {ceny.mean()} zł") 
print(f"Najdroższy produkt: {nazwy[ceny.argmax()]} ({ceny.max()} zł)") 
print(f"Najtańszy produkt: {nazwy[ceny.argmin()]} ({ceny.min()} zł)")

Średnia cena: 1171.0 zł
Najdroższy produkt: Laptop (3499 zł)
Najtańszy produkt: Ładowarka (89 zł)


In [44]:
wartosci_produktow = ceny * ilosci_magazyn 
print(f"Łączna wartość całego magazynu: {wartosci_produktow.sum()} zł")

Łączna wartość całego magazynu: 549465 zł


In [45]:
ceny_rabat = ceny * 0.85 
ceny_vat = ceny * 1.23  
powyzej_1000 = (ceny > 1000).sum() 

print(f"Produkty powyżej 1000 zł: {powyzej_1000}") 

Produkty powyżej 1000 zł: 4


In [46]:
maska_ocena = oceny_klientow >= 4.5 
print("Produkty z wysoką oceną:", nazwy[maska_ocena]) 

maska_tanie = ceny < 200
print("Produkty poniżej 200 zł:", nazwy[maska_tanie])

Produkty z wysoką oceną: ['Laptop' 'Smartfon' 'Słuchawki' 'Monitor']
Produkty poniżej 200 zł: ['Ładowarka' 'Mysz']


In [48]:
maska_niski_stan = ilosci_magazyn < 30
print("Niski stan magazynowy:", nazwy[maska_niski_stan]) 

wartosc_niskich = wartosci_produktow[maska_niski_stan].sum()
print(f"Wartość produktów z niskim stanem: {wartosc_niskich} zł")

Niski stan magazynowy: ['Laptop' 'Monitor']
Wartość produktów z niskim stanem: 86962 zł


In [49]:
maska_okazja = (oceny_klientow >= 4.5) & (ceny < 1000) 
print("Okazje (wysoka ocena + niska cena):", nazwy[maska_okazja])

srednia_wysoka = ceny[oceny_klientow >= 4.0].mean()
srednia_niska = ceny[oceny_klientow < 4.0].mean()
print(f"Średnia cena (ocena >= 4.0): {srednia_wysoka:.2f} zł")
print(f"Średnia cena (ocena < 4.0): {srednia_niska:.2f} zł")

Okazje (wysoka ocena + niska cena): ['Słuchawki']
Średnia cena (ocena >= 4.0): 1446.14 zł
Średnia cena (ocena < 4.0): 529.00 zł
